// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmp-tSE5xyNFdFZRne3ISYMnT527c577k',
    appId: '1:592584084591:web:d82fbe73247f3f7643919a',
    messagingSenderId: '592584084591',
    projectId: 'psyeasy-7fa5a',
    authDomain: 'psyeasy-7fa5a.firebaseapp.com',
    storageBucket: 'psyeasy-7fa5a.appspot.com',
    measurementId: 'G-LZXR2MZ5WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB5ruYujNncdvlLXod8hpWqV2b0QHgWcw',
    appId: '1:592584084591:android:154582433d387bbf43919a',
    messagingSenderId: '592584084591',
    projectId: 'psyeasy-7fa5a',
    storageBucket: 'psyeasy-7fa5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mM7F3Pxh7AxVUeX3CTRu9mrHF3RhpK0',
    appId: '1:592584084591:ios:af8b46d5f2a85f2d43919a',
    messagingSenderId: '592584084591',
    projectId: 'psyeasy-7fa5a',
    storageBucket: 'psyeasy-7fa5a.appspot.com',
    iosBundleId: 'com.example.psyeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mM7F3Pxh7AxVUeX3CTRu9mrHF3RhpK0',
    appId: '1:592584084591:ios:af8b46d5f2a85f2d43919a',
    messagingSenderId: '592584084591',
    projectId: 'psyeasy-7fa5a',
    storageBucket: 'psyeasy-7fa5a.appspot.com',
    iosBundleId: 'com.example.psyeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmp-tSE5xyNFdFZRne3ISYMnT527c577k',
    appId: '1:592584084591:web:179ff76456d013f943919a',
    messagingSenderId: '592584084591',
    projectId: 'psyeasy-7fa5a',
    authDomain: 'psyeasy-7fa5a.firebaseapp.com',
    storageBucket: 'psyeasy-7fa5a.appspot.com',
    measurementId: 'G-EL63F6MWFE',
  );
}
